language: php
sudo: false

php:
  - 5.5
  - 5.6
  - 7.0

mysql:
  database: drupal
  username: root
  encoding: utf8

before_install:
  # Remove Xdebug as we don't need it.
  - phpenv config-rm xdebug.ini || true

  # Update composer.
  - composer --verbose self-update

  # Create database.
  - mysql -e 'CREATE DATABASE drupal;'

  # Add composer bin directory to the path.
  - export PATH="$HOME/.composer/vendor/bin:$PATH"

install:
  # Install Drush.
  - composer global require drush/drush:dev-master

  # Download & Install Drupal.
  - drush --yes dl drupal-7 --drupal-project-rename=drupal
  - cd drupal
  - drush --verbose site-install --db-url=mysql://root:@127.0.0.1/drupal --yes

script:
  - drush status
